import 'package:hive/hive.dart';

part 'student.g.dart';
//name of file auto generated by hive

@HiveType(typeId: 1)
class Student {
  Student({
    //student constructor
    required this.firstName,
    required this.lastName,
    required this.id,
    this.grade = '',
    this.charger = false,
  });

  @HiveField(0)
  String id;

  @HiveField(1)
  String firstName;

  @HiveField(2)
  String lastName;

  @HiveField(3)
  String grade;

  @HiveField(4)
  bool charger;
}
